# Generated by Django 5.2.5 on 2025-11-30 09:14

from django.db import migrations
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Perumahan = apps.get_model('core', 'Perumahan')
    for perumahan in Perumahan.objects.all():
        if not perumahan.slug:
            perumahan.slug = slugify(perumahan.name)
            perumahan.save()

def reverse_populate_slugs(apps, schema_editor):
    # Nothing to reverse
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
    ]
